# CMake generated Testfile for 
# Source directory: D:/CodexBar/WinCodexBar/tests
# Build directory: D:/CodexBar/WinCodexBar/build_vs2019/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_RateWindow]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_RateWindow.exe")
  set_tests_properties([=[tst_RateWindow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;49;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_RateWindow]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_RateWindow.exe")
  set_tests_properties([=[tst_RateWindow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;49;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_RateWindow]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_RateWindow.exe")
  set_tests_properties([=[tst_RateWindow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;49;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_RateWindow]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_RateWindow.exe")
  set_tests_properties([=[tst_RateWindow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;49;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_RateWindow]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_UsagePace]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_UsagePace.exe")
  set_tests_properties([=[tst_UsagePace]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;59;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_UsagePace]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_UsagePace.exe")
  set_tests_properties([=[tst_UsagePace]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;59;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_UsagePace]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_UsagePace.exe")
  set_tests_properties([=[tst_UsagePace]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;59;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_UsagePace]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_UsagePace.exe")
  set_tests_properties([=[tst_UsagePace]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;59;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_UsagePace]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_Localization]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_Localization.exe")
  set_tests_properties([=[tst_Localization]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;81;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_Localization]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_Localization.exe")
  set_tests_properties([=[tst_Localization]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;81;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_Localization]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_Localization.exe")
  set_tests_properties([=[tst_Localization]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;81;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_Localization]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_Localization.exe")
  set_tests_properties([=[tst_Localization]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;81;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_Localization]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_TextParser]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_TextParser.exe")
  set_tests_properties([=[tst_TextParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;92;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_TextParser]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_TextParser.exe")
  set_tests_properties([=[tst_TextParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;92;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_TextParser]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_TextParser.exe")
  set_tests_properties([=[tst_TextParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;92;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_TextParser]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_TextParser.exe")
  set_tests_properties([=[tst_TextParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;92;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_TextParser]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_ZaiProvider]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_ZaiProvider.exe")
  set_tests_properties([=[tst_ZaiProvider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;100;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_ZaiProvider]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_ZaiProvider.exe")
  set_tests_properties([=[tst_ZaiProvider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;100;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_ZaiProvider]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_ZaiProvider.exe")
  set_tests_properties([=[tst_ZaiProvider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;100;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_ZaiProvider]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_ZaiProvider.exe")
  set_tests_properties([=[tst_ZaiProvider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;100;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_ZaiProvider]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_CostUsageScanner]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_CostUsageScanner.exe")
  set_tests_properties([=[tst_CostUsageScanner]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;113;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_CostUsageScanner]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_CostUsageScanner.exe")
  set_tests_properties([=[tst_CostUsageScanner]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;113;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_CostUsageScanner]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_CostUsageScanner.exe")
  set_tests_properties([=[tst_CostUsageScanner]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;113;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_CostUsageScanner]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_CostUsageScanner.exe")
  set_tests_properties([=[tst_CostUsageScanner]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;113;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_CostUsageScanner]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_ProviderPipeline]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_ProviderPipeline.exe")
  set_tests_properties([=[tst_ProviderPipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;121;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_ProviderPipeline]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_ProviderPipeline.exe")
  set_tests_properties([=[tst_ProviderPipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;121;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_ProviderPipeline]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_ProviderPipeline.exe")
  set_tests_properties([=[tst_ProviderPipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;121;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_ProviderPipeline]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_ProviderPipeline.exe")
  set_tests_properties([=[tst_ProviderPipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;121;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_ProviderPipeline]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_FetchContext]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_FetchContext.exe")
  set_tests_properties([=[tst_FetchContext]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;129;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_FetchContext]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_FetchContext.exe")
  set_tests_properties([=[tst_FetchContext]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;129;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_FetchContext]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_FetchContext.exe")
  set_tests_properties([=[tst_FetchContext]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;129;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_FetchContext]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_FetchContext.exe")
  set_tests_properties([=[tst_FetchContext]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;129;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_FetchContext]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_CookieImporter]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_CookieImporter.exe")
  set_tests_properties([=[tst_CookieImporter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;137;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_CookieImporter]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_CookieImporter.exe")
  set_tests_properties([=[tst_CookieImporter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;137;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_CookieImporter]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_CookieImporter.exe")
  set_tests_properties([=[tst_CookieImporter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;137;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_CookieImporter]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_CookieImporter.exe")
  set_tests_properties([=[tst_CookieImporter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;137;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_CookieImporter]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_ConPTYSession]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_ConPTYSession.exe")
  set_tests_properties([=[tst_ConPTYSession]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;145;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_ConPTYSession]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_ConPTYSession.exe")
  set_tests_properties([=[tst_ConPTYSession]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;145;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_ConPTYSession]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_ConPTYSession.exe")
  set_tests_properties([=[tst_ConPTYSession]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;145;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_ConPTYSession]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_ConPTYSession.exe")
  set_tests_properties([=[tst_ConPTYSession]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;145;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_ConPTYSession]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tst_PerProviderCostUsage]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Debug/tst_PerProviderCostUsage.exe")
  set_tests_properties([=[tst_PerProviderCostUsage]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;153;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tst_PerProviderCostUsage]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/Release/tst_PerProviderCostUsage.exe")
  set_tests_properties([=[tst_PerProviderCostUsage]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;153;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tst_PerProviderCostUsage]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/MinSizeRel/tst_PerProviderCostUsage.exe")
  set_tests_properties([=[tst_PerProviderCostUsage]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;153;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tst_PerProviderCostUsage]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PATH=D:/QT_5152/6.5.2/msvc2019_64/bin" "QT_PLUGIN_PATH=D:/QT_5152/6.5.2/msvc2019_64/plugins" "D:/CodexBar/WinCodexBar/build_vs2019/tests/RelWithDebInfo/tst_PerProviderCostUsage.exe")
  set_tests_properties([=[tst_PerProviderCostUsage]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;31;add_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;153;add_wincodexbar_test;D:/CodexBar/WinCodexBar/tests/CMakeLists.txt;0;")
else()
  add_test([=[tst_PerProviderCostUsage]=] NOT_AVAILABLE)
endif()
